name: CI

on:
  pull_request:
  workflow_call:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: "TS Checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile --ignore-scripts

      - name: Lint
        run: bun run lint

      - name: Typecheck
        run: bun run typecheck

  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile --ignore-scripts

      - name: Test (Unit)
        run: bun run test

      - name: Test (Integration)
        run: bun run test:integration
